"""Code generator — converts Strategy IR to executable BaseStrategy Python code.

Usage:
    from src.research.codegen import IRCodeGenerator
    from src.research.strategy_ir import StrategyIR

    ir = StrategyIR.from_file("strategy.yaml")
    gen = IRCodeGenerator()
    source = gen.generate(ir)            # returns Python source string
    StrategyClass = gen.generate_and_load(ir)  # returns importable class
    strategy = StrategyClass(timeframe="1h")
"""

from __future__ import annotations

import importlib.util
import sys
import tempfile
import textwrap
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from src.strategies.base import BaseStrategy

from src.research.strategy_ir import StrategyIR, ConditionDef


class IRCodeGenerator:
    """Generates Python BaseStrategy subclasses from Strategy IR."""

    def generate(self, ir: StrategyIR) -> str:
        """Generate Python source code for a BaseStrategy subclass.

        Returns:
            Complete Python source file as a string.
        """
        class_name = _to_class_name(ir.name)
        indicator_names = ir.get_indicator_names()

        # Build the on_features method body
        entry_long_code = self._condition_to_code(ir.entry_long, "entry_long") if ir.entry_long else ""
        exit_long_code = self._condition_to_code(ir.exit_long, "exit_long") if ir.exit_long else ""
        entry_short_code = self._condition_to_code(ir.entry_short, "entry_short") if ir.entry_short else ""
        exit_short_code = self._condition_to_code(ir.exit_short, "exit_short") if ir.exit_short else ""

        # Build signal generation logic
        signal_logic = self._build_signal_logic(
            ir, entry_long_code, exit_long_code,
            entry_short_code, exit_short_code,
        )

        # Build parameter defaults for __init__
        init_params = ""
        init_body = ""
        for p in ir.parameters:
            default = p.default
            if p.type == "float":
                init_params += f", {p.name}: float = {default}"
            elif p.type == "int":
                init_params += f", {p.name}: int = {default}"
            elif p.type == "bool":
                init_params += f", {p.name}: bool = {default}"
            init_body += f"        self.{p.name} = {p.name}\n"

        source = f'''"""Auto-generated strategy from IR: {ir.name} (v{ir.version}).

Source format: {ir.source_format}
Generated by src/research/codegen.py — do not edit manually.
"""

from __future__ import annotations

import pandas as pd

from src.strategies.base import BaseStrategy
from src.utils.types import Signal, SignalAction


class {class_name}(BaseStrategy):
    """{ir.description or ir.name}"""

    INDICATORS = {indicator_names!r}

    def __init__(self, timeframe: str = "{ir.timeframe}"{init_params}):
        super().__init__(
            name="{_to_snake(ir.name)}",
            markets={ir.markets!r},
            timeframe=timeframe,
        )
{init_body or "        pass"}

    def on_features(self, symbol: str, timeframe: str, features: pd.Series) -> Signal | None:
        prev = self._prev_features
        if prev is None:
            return None

{textwrap.indent(signal_logic, "        ")}
'''
        return source

    def generate_and_load(self, ir: StrategyIR) -> type:
        """Generate code and dynamically import it as a class.

        Returns:
            The generated BaseStrategy subclass (not an instance).
        """
        source = self.generate(ir)
        class_name = _to_class_name(ir.name)
        module_name = f"_gen_{_to_snake(ir.name)}"

        # Write to temp file and import
        tmp = Path(tempfile.mkdtemp()) / f"{module_name}.py"
        tmp.write_text(source)

        spec = importlib.util.spec_from_file_location(module_name, str(tmp))
        if spec is None or spec.loader is None:
            raise RuntimeError(f"Failed to create module spec for {tmp}")
        module = importlib.util.module_from_spec(spec)
        sys.modules[module_name] = module
        spec.loader.exec_module(module)

        return getattr(module, class_name)

    def generate_to_file(self, ir: StrategyIR, output_path: str) -> Path:
        """Generate code and save to a file."""
        source = self.generate(ir)
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(source)
        return path

    # ------------------------------------------------------------------
    # Condition → Python code
    # ------------------------------------------------------------------

    def _condition_to_code(self, cond: ConditionDef, label: str) -> str:
        """Convert a ConditionDef into a Python boolean expression."""
        ctype = cond.type.lower()

        if ctype == "crossover":
            fast, slow = cond.fast, cond.slow
            return (
                f"(prev.get('{fast}') is not None and prev.get('{slow}') is not None "
                f"and features.get('{fast}') is not None and features.get('{slow}') is not None "
                f"and prev['{fast}'] <= prev['{slow}'] and features['{fast}'] > features['{slow}'])"
            )

        elif ctype == "crossunder":
            fast, slow = cond.fast, cond.slow
            return (
                f"(prev.get('{fast}') is not None and prev.get('{slow}') is not None "
                f"and features.get('{fast}') is not None and features.get('{slow}') is not None "
                f"and prev['{fast}'] >= prev['{slow}'] and features['{fast}'] < features['{slow}'])"
            )

        elif ctype == "threshold_above":
            col = cond.column
            thresh = cond.threshold
            return f"(features.get('{col}') is not None and features['{col}'] > {thresh})"

        elif ctype == "threshold_below":
            col = cond.column
            thresh = cond.threshold
            return f"(features.get('{col}') is not None and features['{col}'] < {thresh})"

        elif ctype == "and":
            sub_exprs = []
            for sc in cond.sub_conditions:
                sub_cond = ConditionDef(**sc) if isinstance(sc, dict) else sc
                sub_exprs.append(self._condition_to_code(sub_cond, label))
            return "(" + " and ".join(sub_exprs) + ")" if sub_exprs else "True"

        elif ctype == "or":
            sub_exprs = []
            for sc in cond.sub_conditions:
                sub_cond = ConditionDef(**sc) if isinstance(sc, dict) else sc
                sub_exprs.append(self._condition_to_code(sub_cond, label))
            return "(" + " or ".join(sub_exprs) + ")" if sub_exprs else "False"

        else:
            return f"False  # unknown condition type: {ctype}"

    def _build_signal_logic(
        self,
        ir: StrategyIR,
        entry_long: str,
        exit_long: str,
        entry_short: str,
        exit_short: str,
    ) -> str:
        """Build the signal generation code block."""
        lines = []

        # Long entry
        if entry_long:
            lines.append(f"# Long entry")
            lines.append(f"if {entry_long} and self._position == 'FLAT':")
            lines.append(f"    return Signal(")
            lines.append(f"        symbol=symbol, action=SignalAction.LONG, confidence=1.0,")
            lines.append(f"        strategy_name=self.name, timeframe=timeframe,")
            lines.append(f"    )")
            lines.append("")

        # Long exit
        if exit_long:
            lines.append(f"# Long exit")
            lines.append(f"if {exit_long} and self._position == 'LONG':")
            lines.append(f"    return Signal(")
            lines.append(f"        symbol=symbol, action=SignalAction.CLOSE, confidence=1.0,")
            lines.append(f"        strategy_name=self.name, timeframe=timeframe,")
            lines.append(f"    )")
            lines.append("")

        # Short entry
        if entry_short:
            lines.append(f"# Short entry")
            lines.append(f"if {entry_short} and self._position == 'FLAT':")
            lines.append(f"    return Signal(")
            lines.append(f"        symbol=symbol, action=SignalAction.SHORT, confidence=1.0,")
            lines.append(f"        strategy_name=self.name, timeframe=timeframe,")
            lines.append(f"    )")
            lines.append("")

        # Short exit
        if exit_short:
            lines.append(f"# Short exit")
            lines.append(f"if {exit_short} and self._position == 'SHORT':")
            lines.append(f"    return Signal(")
            lines.append(f"        symbol=symbol, action=SignalAction.CLOSE, confidence=1.0,")
            lines.append(f"        strategy_name=self.name, timeframe=timeframe,")
            lines.append(f"    )")
            lines.append("")

        lines.append("return None")
        return "\n".join(lines)


# ---------------------------------------------------------------------------
# Naming helpers
# ---------------------------------------------------------------------------

def _to_class_name(name: str) -> str:
    """Convert strategy name to PascalCase class name."""
    # Replace non-alphanumeric with space, title case, remove spaces
    clean = "".join(c if c.isalnum() else " " for c in name)
    return "".join(word.capitalize() for word in clean.split()) + "Strategy"


def _to_snake(name: str) -> str:
    """Convert strategy name to snake_case."""
    clean = "".join(c if c.isalnum() else "_" for c in name.lower())
    # Collapse multiple underscores
    while "__" in clean:
        clean = clean.replace("__", "_")
    return clean.strip("_")
