"""Auto-generated strategy from IR: NL EMA Cross (v1.0).

Source format: natural_language
Generated by src/research/codegen.py — do not edit manually.
"""

from __future__ import annotations

import pandas as pd

from src.strategies.base import BaseStrategy
from src.utils.types import Signal, SignalAction


class NlEmaCrossStrategy(BaseStrategy):
    """Buy when 9 EMA crosses above 21 EMA, sell when 9 EMA crosses below"""

    INDICATORS = ['ema_9', 'ema_21']

    def __init__(self, timeframe: str = "1h"):
        super().__init__(
            name="nl_ema_cross",
            markets=['BTCUSDT'],
            timeframe=timeframe,
        )
        pass

    def on_features(self, symbol: str, timeframe: str, features: pd.Series) -> Signal | None:
        prev = self._prev_features
        if prev is None:
            return None

        # Long entry
        if (prev.get('EMA_9') is not None and prev.get('EMA_21') is not None and features.get('EMA_9') is not None and features.get('EMA_21') is not None and prev['EMA_9'] <= prev['EMA_21'] and features['EMA_9'] > features['EMA_21']) and self._position == 'FLAT':
            return Signal(
                symbol=symbol, action=SignalAction.LONG, confidence=1.0,
                strategy_name=self.name, timeframe=timeframe,
            )

        # Long exit
        if (prev.get('EMA_9') is not None and prev.get('EMA_21') is not None and features.get('EMA_9') is not None and features.get('EMA_21') is not None and prev['EMA_9'] >= prev['EMA_21'] and features['EMA_9'] < features['EMA_21']) and self._position == 'LONG':
            return Signal(
                symbol=symbol, action=SignalAction.CLOSE, confidence=1.0,
                strategy_name=self.name, timeframe=timeframe,
            )

        return None
